# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_version = "2.3.8"
  config.vm.box_check_update = false
  config.vm.hostname = "networking-lab"

  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "bootstrap", type: "shell", inline: <<-SHELL
    apt-get update -y
  SHELL
end
